### ISSUE TITLE
win: not working examples

### ISSUE THREAD

**Issue by looooo** [looooo/pivy#20]
- [ ] 09.1:

```
python 09.1.Print.py 01.1.Windmill.iv test.ps
To print the scene: press the 'p' key while in picking mode
Traceback (most recent call last):
  File "09.1.Print.py", line 145, in <module>
    main()
  File "09.1.Print.py", line 129, in main
    viewer = SoGuiExaminerViewer(appWindow, "None", TRUE, SoGuiExaminerViewer.BUILD_ALL, SoGuiExaminerViewer.EDITOR)
AttributeError: type object 'SoGui_Quarter_Wrapper' has no attribute 'BUILD_ALL'
```

- [ ] 09.4:
```
python 09.4.PickAction.py
Traceback (most recent call last):
  File "09.4.PickAction.py", line 131, in <module>
    main()
  File "09.4.PickAction.py", line 113, in main
    myViewer.setViewing(0)
AttributeError: 'SoGui_Quarter_Wrapper' object has no attribute 'setViewing'
```

- [ ] 10.6
```
python 10.6.PickFilterTopLevel.py
Traceback (most recent call last):
  File "10.6.PickFilterTopLevel.py", line 95, in <module>
    main()
  File "10.6.PickFilterTopLevel.py", line 81, in main
    viewer2 = SoGuiExaminerViewer()
TypeError: __init__() missing 1 required positional argument: 'mainwindow'
```

- [ ] 10.8 / 14.2 / 16.2
```
10.8.PickFilterNodeKit.py
The SoGuiMaterialEditor node has not been implemented in the SoGui bindings of Coin!
```

- [ ] 13.2/3/8 (working but error printed)
```
python 13.2.ElapsedTime.py
TypeError: expected a sequence with 2 shorts
```

- [ ] 13.4/5: some clicks are missing

- [ ] 16.1
```
python 16.1.Overlay.py
Traceback (most recent call last):
  File "16.1.Overlay.py", line 79, in <module>
    main()
  File "16.1.Overlay.py", line 70, in main
    myViewer.setOverlayColorMap(1, 1, color)
AttributeError: 'SoGui_Quarter_Wrapper' object has no attribute 'setOverlayColorMap'
```

- [ ] 17.1
```
python 17.1.ColorIndex.py
Traceback (most recent call last):
  File "17.1.ColorIndex.py", line 34, in <module>
    from OpenGL.GLX import *
  File "C:\Users\fc_builder\Miniconda3\envs\pivy\lib\site-packages\OpenGL\GLX\__init__.py", line 3, in <module>
    from OpenGL.GLX.VERSION.GLX_1_0 import *
  File "C:\Users\fc_builder\Miniconda3\envs\pivy\lib\site-packages\OpenGL\GLX\VERSION\GLX_1_0.py", line 14, in <mo
    from OpenGL.raw.GLX.VERSION.GLX_1_0 import *
  File "C:\Users\fc_builder\Miniconda3\envs\pivy\lib\site-packages\OpenGL\raw\GLX\VERSION\GLX_1_0.py", line 43, in
    @_p.types(ctypes.POINTER(_cs.XVisualInfo),ctypes.POINTER(_cs.Display),_cs.c_int,ctypes.POINTER(_cs.c_int))
  File "C:\Users\fc_builder\Miniconda3\envs\pivy\lib\site-packages\OpenGL\raw\GLX\VERSION\GLX_1_0.py", line 13, in
    return _p.createFunction( function,_p.PLATFORM.GLX,'GLX_VERSION_GLX_1_0',error_checker=_errors._error_checker)
AttributeError: 'Win32Platform' object has no attribute 'GLX'
```

- [ ] 17.3
```
This example is not functional as it is GLX dependent!
```

**Comment by InventorMentor** [comment]
Thanks for the list ;-) I'm not a particular supporter of the SoGui binding, but prefer using pivy.quarter or pivy.gui.soqt, directly. Though, "encapsulate what varies" is generally adviseable it does not seem that these two gui bindings where designed to be feature- and behaviour-wise identical in all aspects.

From my point of view you may want to delete from your list above:
17.3 - is a glx dependend version of the cross-platform example 17.2 and therefore not necessarily of general interest  
16.1 - implementation of overlay scenegraphs use a nowadays hardly availble (legacy?) overlay add-on feature available only to some versions of X11 not distributed by most linux distros, is therefore in its current implementation platform dependend and various solutions exist in Qt to replace this functionality from the application side if really needed (e.g. alpha blending and other overlay techniques with QWidgets / painters come to mind)

Same applies to examples 10.8 / 14.2 / 16.2 from my point of view (nice to have, easy Qt-wise if needed from the application side)

Using sogui with backend soqt should fix some of the other issues listed above. So long ... I'm still trying to find some time to compile a patched pyside and test 10.2 against your recent commits. Also, I could not yet figure out a test case for the problem your recent threading fix to pivy-quarter has solved. Examples 10.6 / 13.4 / 13.5 still have the known issues for me with pivy.quarter.

**Comment by looooo** [comment]
Not sure if this is still an issue.nclosing it for now
